[build]
builder = "nixpacks"

[build.env]
NIXPACKS_NO_CACHE = "1"
NIXPACKS_PYTHON_VERSION = "3.11"

[deploy]
startCommand = "gunicorn --worker-class gevent -w 1 --bind 0.0.0.0:$PORT app:app"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
